---
- hosts: localhost
  become: yes
  tasks:
  - name: Create user 'aducastel' and setup SSH
    ansible.builtin.user:
      name: aducastel
      shell: /bin/bash

  - name: Add public key to authorized keys for 'aducastel'
    ansible.builtin.authorized_key:
      user: aducastel
      state: present
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPQJ7bDKP7n4H71H6Qr/opqI+Lgx+SKN9CDk887ta7Jp aducastel"

  - name: Give 'aducastel' sudo privileges
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      line: 'aducastel ALL=(ALL) NOPASSWD: ALL'

  - name: Upgrade all packages
    apt:
      upgrade: dist
      update_cache: yes

  - name: Install packages
    apt:
      name:
        - nvme-cli
        - apparmor
        - ntp
      state: present

  - name: Deactivate swap
    command: swapoff -a

  - name: Update initramfs
    command: update-initramfs -u

  - name: Remove swap.img if exists
    file:
      path: /swap.img
      state: absent

  - name: Deactivate auto-upgrades
    copy:
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      content: |
        APT::Periodic::Update-Package-Lists "0";
        APT::Periodic::Unattended-Upgrade "0";

  - name: Remove unattended-upgrades package
    apt:
      name: unattended-upgrades
      state: absent

  - name: Create /etc/ntp.conf file
    copy:
      dest: /etc/ntp.conf
      content: |
        driftfile /var/lib/ntp/ntp.drift
        leapfile /usr/share/zoneinfo/leap-seconds.list
        statistics loopstats peerstats clockstats
        filegen loopstats file loopstats type day enable
        filegen peerstats file peerstats type day enable
        filegen clockstats file clockstats type day enable

        server time1.google.com iburst
        server time2.google.com iburst
        server time3.google.com iburst
        server time4.google.com iburst

        # By default, exchange time with everybody, but don't allow configuration.
        restrict -4 default kod notrap nomodify nopeer noquery limited
        restrict -6 default kod notrap nomodify nopeer noquery limited
        restrict 127.0.0.1
        restrict ::1
        restrict source notrap nomodify noquery

  - name: Enable ntp service
    ansible.builtin.systemd:
      name: ntp
      state: started
      enabled: yes

  - name: Remove /etc/resolv.conf
    file:
      path: /etc/resolv.conf
      state: absent

  - name: Add DNS entries to /etc/resolv.conf
    copy:
      dest: /etc/resolv.conf
      content: |
        nameserver 8.8.8.8
        nameserver 1.1.1.1

  - name: Disable systemd-resolved service
    ansible.builtin.systemd:
      name: systemd-resolved
      state: stopped
      enabled: no

  - name: Create /etc/systemd/system/fake-resolved.service file
    copy:
      dest: /etc/systemd/system/fake-resolved.service
      content: |
        [Unit]
        Description=Systemd resolved substitute for Kosmos 
        After=network.target

        [Service]
        Type=oneshot
        ExecStart=sh -c "mkdir -p /var/run/systemd/resolve/; cp /etc/resolv.conf /var/run/systemd/resolve/resolv.conf"
        User=root
        Group=root
        RemainAfterExit=yes

        [Install]
        WantedBy=multi-user.target

  - name: Reload systemd daemons
    command: systemctl daemon-reload

  - name: Enable fake-resolved service
    ansible.builtin.systemd:
      name: fake-resolved.service
      state: started
      enabled: yes
